name: movie_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.5
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  firebase_core: ^2.5.0
  firebase_auth: ^4.2.6
  google_sign_in: ^5.4.4
  json_annotation: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  analyzer: ^5.5.0

flutter:

  uses-material-design: true

  assets:
    - lib/assets/images/image_demo.png
    - lib/assets/images/login_home_image.png
    - lib/assets/images/facebook.png
    - lib/assets/images/google.png
    - lib/assets/images/apple.png
    - lib/assets/images/movie_logo.png
    - lib/assets/images/poster_demo.jpeg