name: movie_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.5
  json_serializable: ^6.6.1
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - lib/assets/images/image_demo.png
    - lib/assets/images/login_home_image.png
    - lib/assets/images/facebook.png
    - lib/assets/images/google.png
    - lib/assets/images/apple.png
    - lib/assets/images/movie_logo.png
    - lib/assets/images/poster_demo.jpeg