// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlLDx6kKJjTDyljACQV4YrVdpcNEizhdA',
    appId: '1:183284296814:web:bdfb0b52a6c3f3a37a8a7f',
    messagingSenderId: '183284296814',
    projectId: 'movie-flutter-1fcd9',
    authDomain: 'movie-flutter-1fcd9.firebaseapp.com',
    storageBucket: 'movie-flutter-1fcd9.appspot.com',
    measurementId: 'G-XWLWBX53Q1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB-LB6J_5EQ01swluz_HU_g5nBOsL2IPw',
    appId: '1:183284296814:ios:62650782b61f92207a8a7f',
    messagingSenderId: '183284296814',
    projectId: 'movie-flutter-1fcd9',
    storageBucket: 'movie-flutter-1fcd9.appspot.com',
    iosClientId: '183284296814-qgc4uv2teumd4effjo6g48htucjemfbi.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieFlutter',
  );
}
